apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: necklace
metrics:
  enabled: true
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"